/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.cli.exceptions.wrappers;

import org.eclipse.epsilon.cli.Logger;
import org.eclipse.epsilon.cli.exceptions.CommandLineInterfaceException;

public abstract class CommandLineInteraceExceptionWithUnderlyingCause extends CommandLineInterfaceException {

	// Generated by Eclipse
	private static final long serialVersionUID = 3952481846522262722L;
	
	protected CommandLineInteraceExceptionWithUnderlyingCause(String message, Throwable cause) {
		super(message, cause);
	}
	
	protected CommandLineInteraceExceptionWithUnderlyingCause(String message, String cause) {
		super(message, new StringWrappingException(cause));
	}

	public final void describeTo(Logger logger) {
		logger.append(getMessage() + ":");
		logger.appendNewLine();
		logger.append(getCause());
	}
	
	
	private static class StringWrappingException extends Exception {
		
		// Generated by Eclipse
		private static final long serialVersionUID = 5049713621638328673L;

		public StringWrappingException(String cause) {
			super(cause);
		}

		@Override
		public String toString() {
			return getMessage();
		}
	}
}
