/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.cli.exceptions.wrappers;

import java.io.File;


public class ModelStorageException extends CommandLineInteraceExceptionWithUnderlyingCause {

	// Generated by Eclipse
	private static final long serialVersionUID = 7628534274865393901L;
	
	
	public ModelStorageException(File destination, String cause) {
		super("Error encountered whilst saving model " + destination.getName(), cause);
	}
}
