/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.cli.exceptions;

import org.eclipse.epsilon.cli.Logger;


public abstract class CommandLineInterfaceException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = -8246525690901802184L;

	protected CommandLineInterfaceException(String message) {
		super(message);
	}
	
	protected CommandLineInterfaceException(String message, Throwable cause) {
		super(message, cause);
	}
	
	
	public abstract void describeTo(Logger logger);
}
