/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.cli.exceptions;

import java.io.File;
import java.io.PrintStream;

public class LoggingException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = -7318310630307422818L;

	private final String logContents;
	
	public LoggingException(File logDestination, String logContents, Throwable cause) {
		super("Error encountered whilst writing to log file " + logDestination.getName() + ":", cause);
		
		this.logContents = logContents;
	}

	public void describeTo(PrintStream err) {
		err.println(getMessage());
		err.println(getCause());
		err.println("The log file would have contained the following:");
		err.println(logContents);
	}
}
