/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.cli.exceptions;

import java.util.List;

import org.eclipse.epsilon.cli.Logger;
import org.eclipse.epsilon.cli.domain.Program;
import org.eclipse.epsilon.commons.parse.problem.ParseProblem;

public class ParsingFailedException extends CommandLineInterfaceException {

	// Generated by Eclipse
	private static final long serialVersionUID = -2182041797906225415L;

	private final List<ParseProblem> parseProblems;
	
	public ParsingFailedException(Program program, List<ParseProblem> parseProblems) {
		super("Problems encountered whilst parsing " + program.getName());
		
		this.parseProblems = parseProblems;
	}

	public void describeTo(Logger logger) {
		logger.append(getMessage() + ":");

		for (ParseProblem problem : parseProblems) {
			logger.appendNewLine();
			logger.append("\t" + problem.toString());
		}
	}
}
