/*******************************************************************************
 * Copyright (c) 2011 The University of York.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Louis Rose - initial API and implementation
 ******************************************************************************/
package org.eclipse.epsilon.cli.exceptions;

import org.eclipse.epsilon.cli.Logger;

public class UnknownFileExtensionException extends CommandLineInterfaceException {

	// Generated by Eclipse
	private static final long serialVersionUID = -8339677527844990877L;

	public UnknownFileExtensionException(String extension) {
		super("Unknown file extension: " + extension);
	}

	public void describeTo(Logger logger) {
		logger.append(getMessage());
	}
}
